export const SEED_GROUPS = [
  {
    id: "default",
    name: "Kirkland Disc",
    description: "Weekly pickup games in Kirkland.",
    adminPasscode: "disc-check-dev",
  },
  {
    id: "test",
    name: "Test Group",
    description: "For local development and QA.",
    adminPasscode: "disc-check-dev",
  },
];

export const SEED_GAMES = [
  {
    id: "g1",
    groupId: "default",
    name: "Wednesday Night Disc",
    location: "Heritage Park",
    address: "11100 NE 68th St, Kirkland, WA 98033",
    weekday: 3,
    startTime: "18:00:00",
    timezone: "America/Los_Angeles",
    type: "goaltimate",
    target: 8,
    status: "open",
  },
  {
    id: "g-test-1",
    groupId: "test",
    name: "Saturday Morning Test",
    location: "Test Field A",
    address: null,
    weekday: 6,
    startTime: "10:00:00",
    timezone: "America/Los_Angeles",
    type: "goaltimate",
    target: 8,
    status: "open",
  },
  {
    id: "g-test-2",
    groupId: "test",
    name: "Sunday Afternoon Test",
    location: "Test Field B",
    address: null,
    weekday: 0,
    startTime: "14:00:00",
    timezone: "America/Los_Angeles",
    type: "ultimate",
    target: 10,
    status: "open",
  },
  {
    id: "g-test-3",
    groupId: "test",
    name: "Tuesday Evening Test",
    location: "Test Field C",
    address: "123 Test St, Kirkland, WA 98033",
    weekday: 2,
    startTime: "18:30:00",
    timezone: "America/Los_Angeles",
    type: "goaltimate",
    target: 8,
    status: "open",
  },
  {
    id: "g-test-4",
    groupId: "test",
    name: "Thursday Lunch Test",
    location: "Test Field D",
    address: null,
    weekday: 4,
    startTime: "12:00:00",
    timezone: "America/Los_Angeles",
    type: "goaltimate",
    target: 6,
    status: "open",
  },
  {
    id: "g-test-5",
    groupId: "test",
    name: "Friday Night Test",
    location: "Test Field E",
    address: null,
    weekday: 5,
    startTime: "19:00:00",
    timezone: "America/Los_Angeles",
    type: "ultimate",
    target: 12,
    status: "open",
  },
];
